# Generated by Django 3.1.6 on 2021-03-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='mail_body',
            field=models.CharField(default='Mail', max_length=255),
        ),
    ]
