# Generated by Django 3.1.6 on 2021-04-05 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210330_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='discount_pct',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offer_code',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='offers',
            name='mail_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='mail_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='Pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='in_stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offers',
            name='mail_body',
            field=models.CharField(default='Mail', max_length=255, null=True),
        ),
    ]
