# Generated by Django 3.1.6 on 2021-04-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210405_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='mail_subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='mail_body',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='mail_date',
            field=models.DateField(null=True),
        ),
    ]
